eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # eureka默认就是8761端口，为了以后其他服务的开发，这里就采用8761端口
    register-with-eureka: false    #这个配置的作用就是让当前服务不注册到服务端
spring:
  application:
    name: eureka
server:
  port: 8761